"""add vector extension and embedding column

Revision ID: 6adc7a7b9526
Revises: 5b5ec3d57d50
Create Date: 2026-01-19 17:14:38.446979

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "6adc7a7b9526"
down_revision: str | Sequence[str] | None = "5b5ec3d57d50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notes", sa.Column("embedding", Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notes", "embedding")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
